### ISSUE TITLE
nvd cve feed not availabe causing parsing error

### ISSUE THREAD

**Issue by Radu3000** [sepses/cyber-kg-converter#4]
Getting this error:
```
java -jar target\cyber-kg-converter-1.2.0-SNAPSHOTS-jar-with-dependencies.jar -p cve
2020-02-25 11:56:46 INFO  MainParser - start CVE parser
2020-02-25 11:56:46 INFO  Utility - Dummy triplestore is selected
2020-02-25 11:56:47 INFO  CVEParser - Checking resource meta from https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2002.meta
2020-02-25 11:56:48 INFO  CVEParser - generate cve meta model
2020-02-25 11:56:48 INFO  CVEParser - Downloading resource from internet...
2020-02-25 11:56:49 INFO  CVEParser - Downloading resource Done!
2020-02-25 11:56:49 INFO  CVEParser - Unzipping resource to...
2020-02-25 11:56:49 INFO  CVEParser -  Done!
2020-02-25 11:56:49 INFO  CVEParser - Injecting xml file...
Exception in thread "main" java.nio.file.AccessDeniedException:
        at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(Unknown Source)
        at java.nio.file.Files.newByteChannel(Unknown Source)
        at java.nio.file.Files.newByteChannel(Unknown Source)
        at java.nio.file.Files.readAllBytes(Unknown Source)
        at ac.at.tuwien.ifs.sepses.parser.impl.CVEParser.internalCVEParser(CVEParser.java:210)
        at ac.at.tuwien.ifs.sepses.parser.impl.CVEParser.internalExecution(CVEParser.java:125)
        at ac.at.tuwien.ifs.sepses.parser.impl.CVEParser.parse(CVEParser.java:94)
        at ac.at.tuwien.ifs.sepses.MainParser.main(MainParser.java:59)
```
I thought that you said this will be available till August 2020, right?

But this site https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2002.meta is forwarding to another site that says it is no longer available since Oct 16, 2019....

- Any workaround?

Thanks,
Radu

**Comment by fekaputra** [comment]
Hi Radu, we are working on the JSON converter - the first version of it is available now (it's committed), but not yet checked for consistency with other data; so I would wait about a week more for a more stable version of it.

**Comment by kabulkurniawan** [comment]
> Getting this error:
> 
> ```
> java -jar target\cyber-kg-converter-1.2.0-SNAPSHOTS-jar-with-dependencies.jar -p cve
> 2020-02-25 11:56:46 INFO  MainParser - start CVE parser
> 2020-02-25 11:56:46 INFO  Utility - Dummy triplestore is selected
> 2020-02-25 11:56:47 INFO  CVEParser - Checking resource meta from https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2002.meta
> 2020-02-25 11:56:48 INFO  CVEParser - generate cve meta model
> 2020-02-25 11:56:48 INFO  CVEParser - Downloading resource from internet...
> 2020-02-25 11:56:49 INFO  CVEParser - Downloading resource Done!
> 2020-02-25 11:56:49 INFO  CVEParser - Unzipping resource to...
> 2020-02-25 11:56:49 INFO  CVEParser -  Done!
> 2020-02-25 11:56:49 INFO  CVEParser - Injecting xml file...
> Exception in thread "main" java.nio.file.AccessDeniedException:
>         at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
>         at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
>         at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
>         at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(Unknown Source)
>         at java.nio.file.Files.newByteChannel(Unknown Source)
>         at java.nio.file.Files.newByteChannel(Unknown Source)
>         at java.nio.file.Files.readAllBytes(Unknown Source)
>         at ac.at.tuwien.ifs.sepses.parser.impl.CVEParser.internalCVEParser(CVEParser.java:210)
>         at ac.at.tuwien.ifs.sepses.parser.impl.CVEParser.internalExecution(CVEParser.java:125)
>         at ac.at.tuwien.ifs.sepses.parser.impl.CVEParser.parse(CVEParser.java:94)
>         at ac.at.tuwien.ifs.sepses.MainParser.main(MainParser.java:59)
> ```
> 
> I thought that you said this will be available till August 2020, right?
> 
> But this site https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2002.meta is forwarding to another site that says it is no longer available since Oct 16, 2019....
> 
> * Any workaround?
> 
> Thanks, Radu

Hi Radu

The JSON parser is already there,
please try creating a new git clone from the repo again, and install it as shown on the documentation,
don't forget to set up an initial TripleStore i.e. Virtuoso (https://sourceforge.net/projects/virtuoso/)

Best,
Kabul

**Comment by ssfd7** [comment]
Kabul,

Thanks for your answer.  Nice to see that is still maintained.  

Another reason I thought it is not actively maintained is the absence of any data dumps for past three years - please see this link https://sepses.ifs.tuwien.ac.at/dumps/

- Can you please update data dumps too?

Thank you,
Radu

**Comment by kabulkurniawan** [comment]
Hi Radu,

you can find the latest version of the dumps here:

https://sepses.ifs.tuwien.ac.at/index.php/datasets/

Best,
Kabul
