### ISSUE TITLE
Error reported by XML parser: Element or attribute "xmlns:1" do not match QName

### ISSUE THREAD

**Issue by Alessio-85** [sepses/cyber-kg-converter#9]
java -jar target/cyber-kg-converter-1.2.0-SNAPSHOTS-jar-with-dependencies.jar -p cwe  
or 
java -jar target/cyber-kg-converter-1.2.0-SNAPSHOTS-jar-with-dependencies.jar -p capec
or 
java -jar target/cyber-kg-converter-1.2.0-SNAPSHOTS-jar-with-dependencies.jar -p cpe
generate the following error:
Error on line 2 column 79 
  SXXP0003: Error reported by XML parser: Element or attribute "xmlns:1" do not match QName
  production: QName::=(NCName:)?NCName.
Exception in thread "main" java.lang.RuntimeException: net.sf.saxon.s9api.SaxonApiException: org.xml.sax.SAXParseException; lineNumber: 2; columnNumber: 79; Element or attribute "xmlns
:1" do not match QName production: QName::=(NCName:)?NCName.
        at com.taxonic.carml.logical_source_resolver.XPathResolver.getIterableXpathResult(XPathResolver.java:64)
        at com.taxonic.carml.logical_source_resolver.LogicalSourceResolver.lambda$bindSource$0(LogicalSourceResolver.java:16)
        at com.taxonic.carml.engine.TriplesMapper.map(TriplesMapper.java:44)
        at com.taxonic.carml.engine.RmlMapper.map(RmlMapper.java:385)
        at com.taxonic.carml.engine.RmlMapper.lambda$map$2(RmlMapper.java:327)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at com.taxonic.carml.engine.RmlMapper.map(RmlMapper.java:327)
        at ac.at.tuwien.ifs.sepses.helper.XMLParser.Parse(XMLParser.java:41)
        at ac.at.tuwien.ifs.sepses.helper.Utility.checkIsEqualModifedDate(Utility.java:68)
        at ac.at.tuwien.ifs.sepses.parser.impl.CPEParser.getModelFromLastUpdate(CPEParser.java:183)
        at ac.at.tuwien.ifs.sepses.parser.impl.CPEParser.parse(CPEParser.java:77)
        at ac.at.tuwien.ifs.sepses.MainParser.main(MainParser.java:48)
......

is there anything we can do to fix the problem?

java -jar target/cyber-kg-converter-1.2.0-SNAPSHOTS-jar-with-dependencies.jar -p cve  ... it works really well

**Comment by zhang-xh95** [comment]
I have the same issue too. Have you solved this problem?

**Comment by zhang-xh95** [comment]
> java -jar target/cyber-kg-converter-1.2.0-SNAPSHOTS-jar-with-dependencies.jar -p cwe or java -jar target/cyber-kg-converter-1.2.0-SNAPSHOTS-jar-with-dependencies.jar -p capec or java -jar target/cyber-kg-converter-1.2.0-SNAPSHOTS-jar-with-dependencies.jar -p cpe generate the following error: Error on line 2 column 79 SXXP0003: Error reported by XML parser: Element or attribute "xmlns:1" do not match QName production: QName::=(NCName:)?NCName. Exception in thread "main" java.lang.RuntimeException: net.sf.saxon.s9api.SaxonApiException: org.xml.sax.SAXParseException; lineNumber: 2; columnNumber: 79; Element or attribute "xmlns :1" do not match QName production: QName::=(NCName:)?NCName. at com.taxonic.carml.logical_source_resolver.XPathResolver.getIterableXpathResult(XPathResolver.java:64) at com.taxonic.carml.logical_source_resolver.LogicalSourceResolver.lambda$bindSource$0(LogicalSourceResolver.java:16) at com.taxonic.carml.engine.TriplesMapper.map(TriplesMapper.java:44) at com.taxonic.carml.engine.RmlMapper.map(RmlMapper.java:385) at com.taxonic.carml.engine.RmlMapper.lambda$map$2(RmlMapper.java:327) at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133) at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) at com.taxonic.carml.engine.RmlMapper.map(RmlMapper.java:327) at ac.at.tuwien.ifs.sepses.helper.XMLParser.Parse(XMLParser.java:41) at ac.at.tuwien.ifs.sepses.helper.Utility.checkIsEqualModifedDate(Utility.java:68) at ac.at.tuwien.ifs.sepses.parser.impl.CPEParser.getModelFromLastUpdate(CPEParser.java:183) at ac.at.tuwien.ifs.sepses.parser.impl.CPEParser.parse(CPEParser.java:77) at ac.at.tuwien.ifs.sepses.MainParser.main(MainParser.java:48) ......
> 
> is there anything we can do to fix the problem?
> 
> java -jar target/cyber-kg-converter-1.2.0-SNAPSHOTS-jar-with-dependencies.jar -p cve ... it works really well

I have the same issue too. Have you solved this problem?

**Comment by jiangdie666** [comment]
Have you solved this problem?

**Comment by jiangdie666** [comment]
I solved this problem, as long as the jdk minor version can be lowered, I am using 8u251, 64-bit.
